-- -------------------------------------------------------------
--
-- Module: Hlp4
-- Generated by MATLAB(R) 9.2 and the Filter Design HDL Coder 3.1.1.
-- Generated on: 2017-03-24 11:24:59
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- OptimizeForHDL: on
-- ClockEnableInputPort: enable
-- ClockInputPort: clock
-- AddPipelineRegisters: on
-- Name: Hlp4
-- TestBenchName: Hlp4_tb
-- TestBenchStimulus: impulse step ramp chirp noise 

-- Filter Specifications:
--
-- Sample Rate     : 500 kHz
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Passband Edge   : 50 kHz
-- Stopband Atten. : 80 dB
-- Passband Ripple : 0.01 dB
-- Stopband Edge   : 75 kHz
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 86
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
-- Input             : s13,0 -> [-4096 4096)
-- Filter Internals  : Full Precision
--   Output          : s31,17 -> [-8192 8192)  (auto determined)
--   Product         : s28,17 -> [-1024 1024)  (auto determined)
--   Accumulator     : s31,17 -> [-8192 8192)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY Hlp4 IS
   PORT( clock                           :   IN    std_logic; 
         enable                          :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(12 DOWNTO 0); -- sfix13
         filter_out                      :   OUT   std_logic_vector(30 DOWNTO 0)  -- sfix31_En17
         );

END Hlp4;


----------------------------------------------------------------
--Module Architecture: Hlp4
----------------------------------------------------------------
ARCHITECTURE rtl OF Hlp4 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(12 DOWNTO 0); -- sfix13
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En17
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En17
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-15, 16); -- sfix16_En17
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(-37, 16); -- sfix16_En17
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-49, 16); -- sfix16_En17
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-34, 16); -- sfix16_En17
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(14, 16); -- sfix16_En17
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(77, 16); -- sfix16_En17
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(117, 16); -- sfix16_En17
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(90, 16); -- sfix16_En17
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(-13, 16); -- sfix16_En17
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(-152, 16); -- sfix16_En17
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(-243, 16); -- sfix16_En17
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-200, 16); -- sfix16_En17
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(-4, 16); -- sfix16_En17
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(266, 16); -- sfix16_En17
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(448, 16); -- sfix16_En17
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(388, 16); -- sfix16_En17
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(49, 16); -- sfix16_En17
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(-429, 16); -- sfix16_En17
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(-765, 16); -- sfix16_En17
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(-692, 16); -- sfix16_En17
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(-141, 16); -- sfix16_En17
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(657, 16); -- sfix16_En17
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(1243, 16); -- sfix16_En17
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(1172, 16); -- sfix16_En17
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(314, 16); -- sfix16_En17
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(-979, 16); -- sfix16_En17
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(-1976, 16); -- sfix16_En17
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(-1946, 16); -- sfix16_En17
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(-633, 16); -- sfix16_En17
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(1462, 16); -- sfix16_En17
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(3191, 16); -- sfix16_En17
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(3320, 16); -- sfix16_En17
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(1271, 16); -- sfix16_En17
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(-2333, 16); -- sfix16_En17
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(-5688, 16); -- sfix16_En17
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(-6486, 16); -- sfix16_En17
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(-3007, 16); -- sfix16_En17
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(4894, 16); -- sfix16_En17
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(15434, 16); -- sfix16_En17
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(25420, 16); -- sfix16_En17
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(31485, 16); -- sfix16_En17
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(31485, 16); -- sfix16_En17
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(25420, 16); -- sfix16_En17
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(15434, 16); -- sfix16_En17
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(4894, 16); -- sfix16_En17
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(-3007, 16); -- sfix16_En17
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(-6486, 16); -- sfix16_En17
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(-5688, 16); -- sfix16_En17
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(-2333, 16); -- sfix16_En17
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(1271, 16); -- sfix16_En17
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(3320, 16); -- sfix16_En17
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(3191, 16); -- sfix16_En17
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(1462, 16); -- sfix16_En17
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(-633, 16); -- sfix16_En17
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(-1946, 16); -- sfix16_En17
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(-1976, 16); -- sfix16_En17
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(-979, 16); -- sfix16_En17
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(314, 16); -- sfix16_En17
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(1172, 16); -- sfix16_En17
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(1243, 16); -- sfix16_En17
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(657, 16); -- sfix16_En17
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(-141, 16); -- sfix16_En17
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(-692, 16); -- sfix16_En17
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(-765, 16); -- sfix16_En17
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(-429, 16); -- sfix16_En17
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(49, 16); -- sfix16_En17
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(388, 16); -- sfix16_En17
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(448, 16); -- sfix16_En17
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(266, 16); -- sfix16_En17
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(-4, 16); -- sfix16_En17
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(-200, 16); -- sfix16_En17
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(-243, 16); -- sfix16_En17
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(-152, 16); -- sfix16_En17
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(-13, 16); -- sfix16_En17
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(90, 16); -- sfix16_En17
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(117, 16); -- sfix16_En17
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(77, 16); -- sfix16_En17
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(14, 16); -- sfix16_En17
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(-34, 16); -- sfix16_En17
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(-49, 16); -- sfix16_En17
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(-37, 16); -- sfix16_En17
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(-15, 16); -- sfix16_En17
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En17
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En17

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 85); -- sfix13
  SIGNAL product86                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp                         : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product84                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_1                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product83                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_2                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product82                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_3                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product81                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_4                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product80                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_5                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product79                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_6                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product78                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_7                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product77                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_8                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product76                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_9                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product75                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_10                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product74                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_11                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product73                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_12                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product72                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mulpwr2_temp                     : signed(13 DOWNTO 0); -- sfix14
  SIGNAL product71                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_13                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product70                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_14                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product69                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_15                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product68                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_16                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product67                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_17                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product66                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_18                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product65                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_19                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product64                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_20                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product63                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_21                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product62                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_22                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product61                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_23                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product60                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_24                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product59                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_25                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product58                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_26                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product57                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_27                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product56                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_28                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product55                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_29                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product54                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_30                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product53                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_31                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product52                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_32                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product51                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_33                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product50                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_34                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product49                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_35                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product48                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_36                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product47                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_37                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product46                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_38                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product45                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_39                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product44                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_40                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product43                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_41                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product42                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_42                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product41                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_43                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product40                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_44                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product39                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_45                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product38                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_46                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product37                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_47                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product36                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_48                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product35                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_49                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product34                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_50                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product33                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_51                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product32                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_52                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product31                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_53                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product30                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_54                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product29                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_55                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product28                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_56                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product27                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_57                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product26                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_58                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product25                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_59                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product24                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_60                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product23                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_61                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product22                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_62                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product21                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_63                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product20                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_64                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product19                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_65                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product18                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_66                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product17                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_67                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product16                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_68                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product15                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mulpwr2_temp_1                   : signed(13 DOWNTO 0); -- sfix14
  SIGNAL product14                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_69                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product13                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_70                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product12                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_71                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product11                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_72                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product10                        : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_73                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product9                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_74                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product8                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_75                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product7                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_76                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product6                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_77                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product5                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_78                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product4                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_79                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product3                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_80                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL product1                         : signed(27 DOWNTO 0); -- sfix28_En17
  SIGNAL mul_temp_81                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sum_final                        : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp                         : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_2                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_1                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_3                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_2                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_3                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_4                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_3                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_4                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_5                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_4                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_5                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_6                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_5                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_6                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_7                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_6                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_7                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_8                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_7                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_8                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_9                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_8                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_9                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_10                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_9                       : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_10                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_11                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_10                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_11                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_12                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_11                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_12                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_13                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_12                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_13                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_14                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_13                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_14                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_15                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_14                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_15                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_16                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_15                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_16                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_17                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_16                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_17                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_18                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_17                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_18                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_19                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_18                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_19                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_20                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_19                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_20                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_21                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_20                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_21                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_22                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_21                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_22                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_23                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_22                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_23                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_24                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_23                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_24                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_25                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_24                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_25                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_26                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_25                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_26                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_27                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_26                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_27                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_28                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_27                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_28                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_29                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_28                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_29                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_30                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_29                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_30                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_31                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_30                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_31                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_32                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_31                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_32                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_33                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_32                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_33                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_34                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_33                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_34                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_35                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_34                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_35                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_36                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_35                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_36                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_37                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_36                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_37                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_38                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_37                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_38                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_39                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_38                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_39                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_40                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_39                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_40                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_41                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_40                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_41                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum1_42                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_41                      : signed(28 DOWNTO 0); -- sfix29_En17
  SIGNAL sumpipe1_42                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_42                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_2                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_43                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_3                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_44                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_3                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_4                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_45                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_4                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_5                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_46                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_5                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_6                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_47                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_6                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_7                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_48                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_7                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_8                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_49                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_8                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_9                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_50                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_9                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_10                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_51                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_10                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_11                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_52                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_11                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_12                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_53                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_12                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_13                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_54                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_13                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_14                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_55                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_14                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_15                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_56                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_15                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_16                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_57                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_16                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_17                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_58                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_17                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_18                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_59                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_18                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_19                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_60                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_19                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_20                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_61                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_20                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum2_21                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_62                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe2_21                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_63                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_2                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_64                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_3                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_65                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_3                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_4                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_66                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_4                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_5                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_67                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_5                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_6                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_68                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_6                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_7                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_69                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_7                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_8                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_70                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_8                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_9                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_71                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_9                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum3_10                          : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_72                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe3_10                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sumpipe3_11                      : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum4_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_73                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe4_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum4_2                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_74                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe4_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum4_3                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_75                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe4_3                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum4_4                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_76                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe4_4                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum4_5                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_77                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe4_5                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sumpipe4_6                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum5_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_78                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe5_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum5_2                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_79                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe5_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum5_3                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_80                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe5_3                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum6_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_81                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe6_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sumpipe6_2                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL sum7_1                           : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL add_temp_82                      : signed(31 DOWNTO 0); -- sfix32_En17
  SIGNAL sumpipe7_1                       : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL output_typeconvert               : signed(30 DOWNTO 0); -- sfix31_En17
  SIGNAL output_register                  : signed(30 DOWNTO 0); -- sfix31_En17


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 85) <= (OTHERS => (OTHERS => '0'));
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 85) <= delay_pipeline(0 TO 84);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(85) * coeff86;
  product86 <= mul_temp(27 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(83) * coeff84;
  product84 <= mul_temp_1(27 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(82) * coeff83;
  product83 <= mul_temp_2(27 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(81) * coeff82;
  product82 <= mul_temp_3(27 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(80) * coeff81;
  product81 <= mul_temp_4(27 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(79) * coeff80;
  product80 <= mul_temp_5(27 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(78) * coeff79;
  product79 <= mul_temp_6(27 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(77) * coeff78;
  product78 <= mul_temp_7(27 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(76) * coeff77;
  product77 <= mul_temp_8(27 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(75) * coeff76;
  product76 <= mul_temp_9(27 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(74) * coeff75;
  product75 <= mul_temp_10(27 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(73) * coeff74;
  product74 <= mul_temp_11(27 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(72) * coeff73;
  product73 <= mul_temp_12(27 DOWNTO 0);

  mulpwr2_temp <= ('0' & delay_pipeline(71)) WHEN delay_pipeline(71) = "1000000000000"
      ELSE -resize(delay_pipeline(71),14);

  product72 <= resize(mulpwr2_temp(13 DOWNTO 0) & '0' & '0', 28);

  mul_temp_13 <= delay_pipeline(70) * coeff71;
  product71 <= mul_temp_13(27 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(69) * coeff70;
  product70 <= mul_temp_14(27 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(68) * coeff69;
  product69 <= mul_temp_15(27 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(67) * coeff68;
  product68 <= mul_temp_16(27 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(66) * coeff67;
  product67 <= mul_temp_17(27 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(65) * coeff66;
  product66 <= mul_temp_18(27 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(64) * coeff65;
  product65 <= mul_temp_19(27 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(63) * coeff64;
  product64 <= mul_temp_20(27 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(62) * coeff63;
  product63 <= mul_temp_21(27 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(61) * coeff62;
  product62 <= mul_temp_22(27 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(60) * coeff61;
  product61 <= mul_temp_23(27 DOWNTO 0);

  mul_temp_24 <= delay_pipeline(59) * coeff60;
  product60 <= mul_temp_24(27 DOWNTO 0);

  mul_temp_25 <= delay_pipeline(58) * coeff59;
  product59 <= mul_temp_25(27 DOWNTO 0);

  mul_temp_26 <= delay_pipeline(57) * coeff58;
  product58 <= mul_temp_26(27 DOWNTO 0);

  mul_temp_27 <= delay_pipeline(56) * coeff57;
  product57 <= mul_temp_27(27 DOWNTO 0);

  mul_temp_28 <= delay_pipeline(55) * coeff56;
  product56 <= mul_temp_28(27 DOWNTO 0);

  mul_temp_29 <= delay_pipeline(54) * coeff55;
  product55 <= mul_temp_29(27 DOWNTO 0);

  mul_temp_30 <= delay_pipeline(53) * coeff54;
  product54 <= mul_temp_30(27 DOWNTO 0);

  mul_temp_31 <= delay_pipeline(52) * coeff53;
  product53 <= mul_temp_31(27 DOWNTO 0);

  mul_temp_32 <= delay_pipeline(51) * coeff52;
  product52 <= mul_temp_32(27 DOWNTO 0);

  mul_temp_33 <= delay_pipeline(50) * coeff51;
  product51 <= mul_temp_33(27 DOWNTO 0);

  mul_temp_34 <= delay_pipeline(49) * coeff50;
  product50 <= mul_temp_34(27 DOWNTO 0);

  mul_temp_35 <= delay_pipeline(48) * coeff49;
  product49 <= mul_temp_35(27 DOWNTO 0);

  mul_temp_36 <= delay_pipeline(47) * coeff48;
  product48 <= mul_temp_36(27 DOWNTO 0);

  mul_temp_37 <= delay_pipeline(46) * coeff47;
  product47 <= mul_temp_37(27 DOWNTO 0);

  mul_temp_38 <= delay_pipeline(45) * coeff46;
  product46 <= mul_temp_38(27 DOWNTO 0);

  mul_temp_39 <= delay_pipeline(44) * coeff45;
  product45 <= mul_temp_39(27 DOWNTO 0);

  mul_temp_40 <= delay_pipeline(43) * coeff44;
  product44 <= mul_temp_40(27 DOWNTO 0);

  mul_temp_41 <= delay_pipeline(42) * coeff43;
  product43 <= mul_temp_41(27 DOWNTO 0);

  mul_temp_42 <= delay_pipeline(41) * coeff42;
  product42 <= mul_temp_42(27 DOWNTO 0);

  mul_temp_43 <= delay_pipeline(40) * coeff41;
  product41 <= mul_temp_43(27 DOWNTO 0);

  mul_temp_44 <= delay_pipeline(39) * coeff40;
  product40 <= mul_temp_44(27 DOWNTO 0);

  mul_temp_45 <= delay_pipeline(38) * coeff39;
  product39 <= mul_temp_45(27 DOWNTO 0);

  mul_temp_46 <= delay_pipeline(37) * coeff38;
  product38 <= mul_temp_46(27 DOWNTO 0);

  mul_temp_47 <= delay_pipeline(36) * coeff37;
  product37 <= mul_temp_47(27 DOWNTO 0);

  mul_temp_48 <= delay_pipeline(35) * coeff36;
  product36 <= mul_temp_48(27 DOWNTO 0);

  mul_temp_49 <= delay_pipeline(34) * coeff35;
  product35 <= mul_temp_49(27 DOWNTO 0);

  mul_temp_50 <= delay_pipeline(33) * coeff34;
  product34 <= mul_temp_50(27 DOWNTO 0);

  mul_temp_51 <= delay_pipeline(32) * coeff33;
  product33 <= mul_temp_51(27 DOWNTO 0);

  mul_temp_52 <= delay_pipeline(31) * coeff32;
  product32 <= mul_temp_52(27 DOWNTO 0);

  mul_temp_53 <= delay_pipeline(30) * coeff31;
  product31 <= mul_temp_53(27 DOWNTO 0);

  mul_temp_54 <= delay_pipeline(29) * coeff30;
  product30 <= mul_temp_54(27 DOWNTO 0);

  mul_temp_55 <= delay_pipeline(28) * coeff29;
  product29 <= mul_temp_55(27 DOWNTO 0);

  mul_temp_56 <= delay_pipeline(27) * coeff28;
  product28 <= mul_temp_56(27 DOWNTO 0);

  mul_temp_57 <= delay_pipeline(26) * coeff27;
  product27 <= mul_temp_57(27 DOWNTO 0);

  mul_temp_58 <= delay_pipeline(25) * coeff26;
  product26 <= mul_temp_58(27 DOWNTO 0);

  mul_temp_59 <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp_59(27 DOWNTO 0);

  mul_temp_60 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_60(27 DOWNTO 0);

  mul_temp_61 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_61(27 DOWNTO 0);

  mul_temp_62 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_62(27 DOWNTO 0);

  mul_temp_63 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_63(27 DOWNTO 0);

  mul_temp_64 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_64(27 DOWNTO 0);

  mul_temp_65 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_65(27 DOWNTO 0);

  mul_temp_66 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_66(27 DOWNTO 0);

  mul_temp_67 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_67(27 DOWNTO 0);

  mul_temp_68 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_68(27 DOWNTO 0);

  mulpwr2_temp_1 <= ('0' & delay_pipeline(14)) WHEN delay_pipeline(14) = "1000000000000"
      ELSE -resize(delay_pipeline(14),14);

  product15 <= resize(mulpwr2_temp_1(13 DOWNTO 0) & '0' & '0', 28);

  mul_temp_69 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_69(27 DOWNTO 0);

  mul_temp_70 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_70(27 DOWNTO 0);

  mul_temp_71 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_71(27 DOWNTO 0);

  mul_temp_72 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_72(27 DOWNTO 0);

  mul_temp_73 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_73(27 DOWNTO 0);

  mul_temp_74 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_74(27 DOWNTO 0);

  mul_temp_75 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_75(27 DOWNTO 0);

  mul_temp_76 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_76(27 DOWNTO 0);

  mul_temp_77 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_77(27 DOWNTO 0);

  mul_temp_78 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_78(27 DOWNTO 0);

  mul_temp_79 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_79(27 DOWNTO 0);

  mul_temp_80 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_80(27 DOWNTO 0);

  mul_temp_81 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_81(27 DOWNTO 0);

  add_temp <= resize(product86, 29) + resize(product84, 29);
  sum1_1 <= resize(add_temp, 31);

  add_temp_1 <= resize(product83, 29) + resize(product82, 29);
  sum1_2 <= resize(add_temp_1, 31);

  add_temp_2 <= resize(product81, 29) + resize(product80, 29);
  sum1_3 <= resize(add_temp_2, 31);

  add_temp_3 <= resize(product79, 29) + resize(product78, 29);
  sum1_4 <= resize(add_temp_3, 31);

  add_temp_4 <= resize(product77, 29) + resize(product76, 29);
  sum1_5 <= resize(add_temp_4, 31);

  add_temp_5 <= resize(product75, 29) + resize(product74, 29);
  sum1_6 <= resize(add_temp_5, 31);

  add_temp_6 <= resize(product73, 29) + resize(product72, 29);
  sum1_7 <= resize(add_temp_6, 31);

  add_temp_7 <= resize(product71, 29) + resize(product70, 29);
  sum1_8 <= resize(add_temp_7, 31);

  add_temp_8 <= resize(product69, 29) + resize(product68, 29);
  sum1_9 <= resize(add_temp_8, 31);

  add_temp_9 <= resize(product67, 29) + resize(product66, 29);
  sum1_10 <= resize(add_temp_9, 31);

  add_temp_10 <= resize(product65, 29) + resize(product64, 29);
  sum1_11 <= resize(add_temp_10, 31);

  add_temp_11 <= resize(product63, 29) + resize(product62, 29);
  sum1_12 <= resize(add_temp_11, 31);

  add_temp_12 <= resize(product61, 29) + resize(product60, 29);
  sum1_13 <= resize(add_temp_12, 31);

  add_temp_13 <= resize(product59, 29) + resize(product58, 29);
  sum1_14 <= resize(add_temp_13, 31);

  add_temp_14 <= resize(product57, 29) + resize(product56, 29);
  sum1_15 <= resize(add_temp_14, 31);

  add_temp_15 <= resize(product55, 29) + resize(product54, 29);
  sum1_16 <= resize(add_temp_15, 31);

  add_temp_16 <= resize(product53, 29) + resize(product52, 29);
  sum1_17 <= resize(add_temp_16, 31);

  add_temp_17 <= resize(product51, 29) + resize(product50, 29);
  sum1_18 <= resize(add_temp_17, 31);

  add_temp_18 <= resize(product49, 29) + resize(product48, 29);
  sum1_19 <= resize(add_temp_18, 31);

  add_temp_19 <= resize(product47, 29) + resize(product46, 29);
  sum1_20 <= resize(add_temp_19, 31);

  add_temp_20 <= resize(product45, 29) + resize(product44, 29);
  sum1_21 <= resize(add_temp_20, 31);

  add_temp_21 <= resize(product43, 29) + resize(product42, 29);
  sum1_22 <= resize(add_temp_21, 31);

  add_temp_22 <= resize(product41, 29) + resize(product40, 29);
  sum1_23 <= resize(add_temp_22, 31);

  add_temp_23 <= resize(product39, 29) + resize(product38, 29);
  sum1_24 <= resize(add_temp_23, 31);

  add_temp_24 <= resize(product37, 29) + resize(product36, 29);
  sum1_25 <= resize(add_temp_24, 31);

  add_temp_25 <= resize(product35, 29) + resize(product34, 29);
  sum1_26 <= resize(add_temp_25, 31);

  add_temp_26 <= resize(product33, 29) + resize(product32, 29);
  sum1_27 <= resize(add_temp_26, 31);

  add_temp_27 <= resize(product31, 29) + resize(product30, 29);
  sum1_28 <= resize(add_temp_27, 31);

  add_temp_28 <= resize(product29, 29) + resize(product28, 29);
  sum1_29 <= resize(add_temp_28, 31);

  add_temp_29 <= resize(product27, 29) + resize(product26, 29);
  sum1_30 <= resize(add_temp_29, 31);

  add_temp_30 <= resize(product25, 29) + resize(product24, 29);
  sum1_31 <= resize(add_temp_30, 31);

  add_temp_31 <= resize(product23, 29) + resize(product22, 29);
  sum1_32 <= resize(add_temp_31, 31);

  add_temp_32 <= resize(product21, 29) + resize(product20, 29);
  sum1_33 <= resize(add_temp_32, 31);

  add_temp_33 <= resize(product19, 29) + resize(product18, 29);
  sum1_34 <= resize(add_temp_33, 31);

  add_temp_34 <= resize(product17, 29) + resize(product16, 29);
  sum1_35 <= resize(add_temp_34, 31);

  add_temp_35 <= resize(product15, 29) + resize(product14, 29);
  sum1_36 <= resize(add_temp_35, 31);

  add_temp_36 <= resize(product13, 29) + resize(product12, 29);
  sum1_37 <= resize(add_temp_36, 31);

  add_temp_37 <= resize(product11, 29) + resize(product10, 29);
  sum1_38 <= resize(add_temp_37, 31);

  add_temp_38 <= resize(product9, 29) + resize(product8, 29);
  sum1_39 <= resize(add_temp_38, 31);

  add_temp_39 <= resize(product7, 29) + resize(product6, 29);
  sum1_40 <= resize(add_temp_39, 31);

  add_temp_40 <= resize(product5, 29) + resize(product4, 29);
  sum1_41 <= resize(add_temp_40, 31);

  add_temp_41 <= resize(product3, 29) + resize(product1, 29);
  sum1_42 <= resize(add_temp_41, 31);

  temp_process1 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe1_1 <= (OTHERS => '0');
      sumpipe1_2 <= (OTHERS => '0');
      sumpipe1_3 <= (OTHERS => '0');
      sumpipe1_4 <= (OTHERS => '0');
      sumpipe1_5 <= (OTHERS => '0');
      sumpipe1_6 <= (OTHERS => '0');
      sumpipe1_7 <= (OTHERS => '0');
      sumpipe1_8 <= (OTHERS => '0');
      sumpipe1_9 <= (OTHERS => '0');
      sumpipe1_10 <= (OTHERS => '0');
      sumpipe1_11 <= (OTHERS => '0');
      sumpipe1_12 <= (OTHERS => '0');
      sumpipe1_13 <= (OTHERS => '0');
      sumpipe1_14 <= (OTHERS => '0');
      sumpipe1_15 <= (OTHERS => '0');
      sumpipe1_16 <= (OTHERS => '0');
      sumpipe1_17 <= (OTHERS => '0');
      sumpipe1_18 <= (OTHERS => '0');
      sumpipe1_19 <= (OTHERS => '0');
      sumpipe1_20 <= (OTHERS => '0');
      sumpipe1_21 <= (OTHERS => '0');
      sumpipe1_22 <= (OTHERS => '0');
      sumpipe1_23 <= (OTHERS => '0');
      sumpipe1_24 <= (OTHERS => '0');
      sumpipe1_25 <= (OTHERS => '0');
      sumpipe1_26 <= (OTHERS => '0');
      sumpipe1_27 <= (OTHERS => '0');
      sumpipe1_28 <= (OTHERS => '0');
      sumpipe1_29 <= (OTHERS => '0');
      sumpipe1_30 <= (OTHERS => '0');
      sumpipe1_31 <= (OTHERS => '0');
      sumpipe1_32 <= (OTHERS => '0');
      sumpipe1_33 <= (OTHERS => '0');
      sumpipe1_34 <= (OTHERS => '0');
      sumpipe1_35 <= (OTHERS => '0');
      sumpipe1_36 <= (OTHERS => '0');
      sumpipe1_37 <= (OTHERS => '0');
      sumpipe1_38 <= (OTHERS => '0');
      sumpipe1_39 <= (OTHERS => '0');
      sumpipe1_40 <= (OTHERS => '0');
      sumpipe1_41 <= (OTHERS => '0');
      sumpipe1_42 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe1_1 <= sum1_1;
        sumpipe1_2 <= sum1_2;
        sumpipe1_3 <= sum1_3;
        sumpipe1_4 <= sum1_4;
        sumpipe1_5 <= sum1_5;
        sumpipe1_6 <= sum1_6;
        sumpipe1_7 <= sum1_7;
        sumpipe1_8 <= sum1_8;
        sumpipe1_9 <= sum1_9;
        sumpipe1_10 <= sum1_10;
        sumpipe1_11 <= sum1_11;
        sumpipe1_12 <= sum1_12;
        sumpipe1_13 <= sum1_13;
        sumpipe1_14 <= sum1_14;
        sumpipe1_15 <= sum1_15;
        sumpipe1_16 <= sum1_16;
        sumpipe1_17 <= sum1_17;
        sumpipe1_18 <= sum1_18;
        sumpipe1_19 <= sum1_19;
        sumpipe1_20 <= sum1_20;
        sumpipe1_21 <= sum1_21;
        sumpipe1_22 <= sum1_22;
        sumpipe1_23 <= sum1_23;
        sumpipe1_24 <= sum1_24;
        sumpipe1_25 <= sum1_25;
        sumpipe1_26 <= sum1_26;
        sumpipe1_27 <= sum1_27;
        sumpipe1_28 <= sum1_28;
        sumpipe1_29 <= sum1_29;
        sumpipe1_30 <= sum1_30;
        sumpipe1_31 <= sum1_31;
        sumpipe1_32 <= sum1_32;
        sumpipe1_33 <= sum1_33;
        sumpipe1_34 <= sum1_34;
        sumpipe1_35 <= sum1_35;
        sumpipe1_36 <= sum1_36;
        sumpipe1_37 <= sum1_37;
        sumpipe1_38 <= sum1_38;
        sumpipe1_39 <= sum1_39;
        sumpipe1_40 <= sum1_40;
        sumpipe1_41 <= sum1_41;
        sumpipe1_42 <= sum1_42;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  add_temp_42 <= resize(sumpipe1_1, 32) + resize(sumpipe1_2, 32);
  sum2_1 <= add_temp_42(30 DOWNTO 0);

  add_temp_43 <= resize(sumpipe1_3, 32) + resize(sumpipe1_4, 32);
  sum2_2 <= add_temp_43(30 DOWNTO 0);

  add_temp_44 <= resize(sumpipe1_5, 32) + resize(sumpipe1_6, 32);
  sum2_3 <= add_temp_44(30 DOWNTO 0);

  add_temp_45 <= resize(sumpipe1_7, 32) + resize(sumpipe1_8, 32);
  sum2_4 <= add_temp_45(30 DOWNTO 0);

  add_temp_46 <= resize(sumpipe1_9, 32) + resize(sumpipe1_10, 32);
  sum2_5 <= add_temp_46(30 DOWNTO 0);

  add_temp_47 <= resize(sumpipe1_11, 32) + resize(sumpipe1_12, 32);
  sum2_6 <= add_temp_47(30 DOWNTO 0);

  add_temp_48 <= resize(sumpipe1_13, 32) + resize(sumpipe1_14, 32);
  sum2_7 <= add_temp_48(30 DOWNTO 0);

  add_temp_49 <= resize(sumpipe1_15, 32) + resize(sumpipe1_16, 32);
  sum2_8 <= add_temp_49(30 DOWNTO 0);

  add_temp_50 <= resize(sumpipe1_17, 32) + resize(sumpipe1_18, 32);
  sum2_9 <= add_temp_50(30 DOWNTO 0);

  add_temp_51 <= resize(sumpipe1_19, 32) + resize(sumpipe1_20, 32);
  sum2_10 <= add_temp_51(30 DOWNTO 0);

  add_temp_52 <= resize(sumpipe1_21, 32) + resize(sumpipe1_22, 32);
  sum2_11 <= add_temp_52(30 DOWNTO 0);

  add_temp_53 <= resize(sumpipe1_23, 32) + resize(sumpipe1_24, 32);
  sum2_12 <= add_temp_53(30 DOWNTO 0);

  add_temp_54 <= resize(sumpipe1_25, 32) + resize(sumpipe1_26, 32);
  sum2_13 <= add_temp_54(30 DOWNTO 0);

  add_temp_55 <= resize(sumpipe1_27, 32) + resize(sumpipe1_28, 32);
  sum2_14 <= add_temp_55(30 DOWNTO 0);

  add_temp_56 <= resize(sumpipe1_29, 32) + resize(sumpipe1_30, 32);
  sum2_15 <= add_temp_56(30 DOWNTO 0);

  add_temp_57 <= resize(sumpipe1_31, 32) + resize(sumpipe1_32, 32);
  sum2_16 <= add_temp_57(30 DOWNTO 0);

  add_temp_58 <= resize(sumpipe1_33, 32) + resize(sumpipe1_34, 32);
  sum2_17 <= add_temp_58(30 DOWNTO 0);

  add_temp_59 <= resize(sumpipe1_35, 32) + resize(sumpipe1_36, 32);
  sum2_18 <= add_temp_59(30 DOWNTO 0);

  add_temp_60 <= resize(sumpipe1_37, 32) + resize(sumpipe1_38, 32);
  sum2_19 <= add_temp_60(30 DOWNTO 0);

  add_temp_61 <= resize(sumpipe1_39, 32) + resize(sumpipe1_40, 32);
  sum2_20 <= add_temp_61(30 DOWNTO 0);

  add_temp_62 <= resize(sumpipe1_41, 32) + resize(sumpipe1_42, 32);
  sum2_21 <= add_temp_62(30 DOWNTO 0);

  temp_process2 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe2_1 <= (OTHERS => '0');
      sumpipe2_2 <= (OTHERS => '0');
      sumpipe2_3 <= (OTHERS => '0');
      sumpipe2_4 <= (OTHERS => '0');
      sumpipe2_5 <= (OTHERS => '0');
      sumpipe2_6 <= (OTHERS => '0');
      sumpipe2_7 <= (OTHERS => '0');
      sumpipe2_8 <= (OTHERS => '0');
      sumpipe2_9 <= (OTHERS => '0');
      sumpipe2_10 <= (OTHERS => '0');
      sumpipe2_11 <= (OTHERS => '0');
      sumpipe2_12 <= (OTHERS => '0');
      sumpipe2_13 <= (OTHERS => '0');
      sumpipe2_14 <= (OTHERS => '0');
      sumpipe2_15 <= (OTHERS => '0');
      sumpipe2_16 <= (OTHERS => '0');
      sumpipe2_17 <= (OTHERS => '0');
      sumpipe2_18 <= (OTHERS => '0');
      sumpipe2_19 <= (OTHERS => '0');
      sumpipe2_20 <= (OTHERS => '0');
      sumpipe2_21 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe2_1 <= sum2_1;
        sumpipe2_2 <= sum2_2;
        sumpipe2_3 <= sum2_3;
        sumpipe2_4 <= sum2_4;
        sumpipe2_5 <= sum2_5;
        sumpipe2_6 <= sum2_6;
        sumpipe2_7 <= sum2_7;
        sumpipe2_8 <= sum2_8;
        sumpipe2_9 <= sum2_9;
        sumpipe2_10 <= sum2_10;
        sumpipe2_11 <= sum2_11;
        sumpipe2_12 <= sum2_12;
        sumpipe2_13 <= sum2_13;
        sumpipe2_14 <= sum2_14;
        sumpipe2_15 <= sum2_15;
        sumpipe2_16 <= sum2_16;
        sumpipe2_17 <= sum2_17;
        sumpipe2_18 <= sum2_18;
        sumpipe2_19 <= sum2_19;
        sumpipe2_20 <= sum2_20;
        sumpipe2_21 <= sum2_21;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  add_temp_63 <= resize(sumpipe2_1, 32) + resize(sumpipe2_2, 32);
  sum3_1 <= add_temp_63(30 DOWNTO 0);

  add_temp_64 <= resize(sumpipe2_3, 32) + resize(sumpipe2_4, 32);
  sum3_2 <= add_temp_64(30 DOWNTO 0);

  add_temp_65 <= resize(sumpipe2_5, 32) + resize(sumpipe2_6, 32);
  sum3_3 <= add_temp_65(30 DOWNTO 0);

  add_temp_66 <= resize(sumpipe2_7, 32) + resize(sumpipe2_8, 32);
  sum3_4 <= add_temp_66(30 DOWNTO 0);

  add_temp_67 <= resize(sumpipe2_9, 32) + resize(sumpipe2_10, 32);
  sum3_5 <= add_temp_67(30 DOWNTO 0);

  add_temp_68 <= resize(sumpipe2_11, 32) + resize(sumpipe2_12, 32);
  sum3_6 <= add_temp_68(30 DOWNTO 0);

  add_temp_69 <= resize(sumpipe2_13, 32) + resize(sumpipe2_14, 32);
  sum3_7 <= add_temp_69(30 DOWNTO 0);

  add_temp_70 <= resize(sumpipe2_15, 32) + resize(sumpipe2_16, 32);
  sum3_8 <= add_temp_70(30 DOWNTO 0);

  add_temp_71 <= resize(sumpipe2_17, 32) + resize(sumpipe2_18, 32);
  sum3_9 <= add_temp_71(30 DOWNTO 0);

  add_temp_72 <= resize(sumpipe2_19, 32) + resize(sumpipe2_20, 32);
  sum3_10 <= add_temp_72(30 DOWNTO 0);

  temp_process3 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe3_1 <= (OTHERS => '0');
      sumpipe3_2 <= (OTHERS => '0');
      sumpipe3_3 <= (OTHERS => '0');
      sumpipe3_4 <= (OTHERS => '0');
      sumpipe3_5 <= (OTHERS => '0');
      sumpipe3_6 <= (OTHERS => '0');
      sumpipe3_7 <= (OTHERS => '0');
      sumpipe3_8 <= (OTHERS => '0');
      sumpipe3_9 <= (OTHERS => '0');
      sumpipe3_10 <= (OTHERS => '0');
      sumpipe3_11 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe3_1 <= sum3_1;
        sumpipe3_2 <= sum3_2;
        sumpipe3_3 <= sum3_3;
        sumpipe3_4 <= sum3_4;
        sumpipe3_5 <= sum3_5;
        sumpipe3_6 <= sum3_6;
        sumpipe3_7 <= sum3_7;
        sumpipe3_8 <= sum3_8;
        sumpipe3_9 <= sum3_9;
        sumpipe3_10 <= sum3_10;
        sumpipe3_11 <= sumpipe2_21;
      END IF;
    END IF; 
  END PROCESS temp_process3;

  add_temp_73 <= resize(sumpipe3_1, 32) + resize(sumpipe3_2, 32);
  sum4_1 <= add_temp_73(30 DOWNTO 0);

  add_temp_74 <= resize(sumpipe3_3, 32) + resize(sumpipe3_4, 32);
  sum4_2 <= add_temp_74(30 DOWNTO 0);

  add_temp_75 <= resize(sumpipe3_5, 32) + resize(sumpipe3_6, 32);
  sum4_3 <= add_temp_75(30 DOWNTO 0);

  add_temp_76 <= resize(sumpipe3_7, 32) + resize(sumpipe3_8, 32);
  sum4_4 <= add_temp_76(30 DOWNTO 0);

  add_temp_77 <= resize(sumpipe3_9, 32) + resize(sumpipe3_10, 32);
  sum4_5 <= add_temp_77(30 DOWNTO 0);

  temp_process4 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe4_1 <= (OTHERS => '0');
      sumpipe4_2 <= (OTHERS => '0');
      sumpipe4_3 <= (OTHERS => '0');
      sumpipe4_4 <= (OTHERS => '0');
      sumpipe4_5 <= (OTHERS => '0');
      sumpipe4_6 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe4_1 <= sum4_1;
        sumpipe4_2 <= sum4_2;
        sumpipe4_3 <= sum4_3;
        sumpipe4_4 <= sum4_4;
        sumpipe4_5 <= sum4_5;
        sumpipe4_6 <= sumpipe3_11;
      END IF;
    END IF; 
  END PROCESS temp_process4;

  add_temp_78 <= resize(sumpipe4_1, 32) + resize(sumpipe4_2, 32);
  sum5_1 <= add_temp_78(30 DOWNTO 0);

  add_temp_79 <= resize(sumpipe4_3, 32) + resize(sumpipe4_4, 32);
  sum5_2 <= add_temp_79(30 DOWNTO 0);

  add_temp_80 <= resize(sumpipe4_5, 32) + resize(sumpipe4_6, 32);
  sum5_3 <= add_temp_80(30 DOWNTO 0);

  temp_process5 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe5_1 <= (OTHERS => '0');
      sumpipe5_2 <= (OTHERS => '0');
      sumpipe5_3 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe5_1 <= sum5_1;
        sumpipe5_2 <= sum5_2;
        sumpipe5_3 <= sum5_3;
      END IF;
    END IF; 
  END PROCESS temp_process5;

  add_temp_81 <= resize(sumpipe5_1, 32) + resize(sumpipe5_2, 32);
  sum6_1 <= add_temp_81(30 DOWNTO 0);

  temp_process6 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe6_1 <= (OTHERS => '0');
      sumpipe6_2 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe6_1 <= sum6_1;
        sumpipe6_2 <= sumpipe5_3;
      END IF;
    END IF; 
  END PROCESS temp_process6;

  add_temp_82 <= resize(sumpipe6_1, 32) + resize(sumpipe6_2, 32);
  sum7_1 <= add_temp_82(30 DOWNTO 0);

  temp_process7 : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe7_1 <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        sumpipe7_1 <= sum7_1;
      END IF;
    END IF; 
  END PROCESS temp_process7;

  sum_final <= sumpipe7_1;

  output_typeconvert <= sum_final;

  Output_Register_process : PROCESS (clock, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clock'event AND clock = '1' THEN
      IF enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
